# Generated by Django 6.0 on 2026-01-15 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sets', '0007_card_card_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Learn_session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(auto_now_add=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learn_sessions', to='sets.set')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learn_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Log_answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_answer', models.DateTimeField(auto_now_add=True)),
                ('type_of_card', models.CharField(max_length=15)),
                ('logged_question', models.CharField(max_length=80)),
                ('logged_answer', models.CharField(max_length=1)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('is_better', models.CharField(blank=True, max_length=30, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_log', to='learn_sessions.learn_session')),
            ],
        ),
    ]
