# Generated by Django 6.0 on 2025-12-31 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn_sessions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learn_session',
            name='current_card_nr',
        ),
    ]
