# Generated by Django 6.0 on 2026-01-12 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_sessions', '0002_remove_learn_session_current_card_nr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log_answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_answer', models.DateTimeField(auto_now_add=True)),
                ('type_of_card', models.CharField(max_length=15)),
                ('logged_question', models.CharField(max_length=80)),
                ('logged_answer', models.CharField(max_length=1)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_log', to='learn_sessions.learn_session')),
            ],
        ),
    ]
