# Generated by Django 6.0 on 2025-12-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='mastered_lvl',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='set',
            name='sessions_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
