# Generated by Django 6.0 on 2025-12-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0002_card_mastered_lvl_set_sessions_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='answer_image',
            field=models.ImageField(blank=True, null=True, upload_to='cards/answers/'),
        ),
        migrations.AddField(
            model_name='card',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to='cards/questions/'),
        ),
    ]
