# Generated by Django 6.0 on 2025-12-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0003_card_answer_image_card_question_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='answer',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='question',
            field=models.TextField(blank=True),
        ),
    ]
