# Generated by Django 6.0 on 2026-01-06 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0004_alter_card_answer_alter_card_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card_closed_q',
            fields=[
                ('card_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sets.card')),
            ],
            bases=('sets.card',),
        ),
        migrations.CreateModel(
            name='Card_answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('parent_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_answers', to='sets.card_closed_q')),
            ],
        ),
    ]
