# Generated by Django 6.0 on 2026-01-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0005_card_closed_q_card_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='card_answers',
            name='letter',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
