# Generated by Django 6.0 on 2026-01-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0006_card_answers_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_type',
            field=models.TextField(default='open_card'),
        ),
    ]
